name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump PHP version
        run: php -v

      - name: Validate composer.json
        run: composer validate --strict

      - name: Lint all PHP files
        run: composer run qa:lint

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          retry_wait_seconds: 30
          command: |
            composer update --optimize-autoloader --no-interaction --ansi --no-progress --prefer-dist
            composer info -D

#      - name: Run static code analyser
#        run: composer run qa:phpstan

      - name: Run unit tests
        run: composer run test:phpunit
